### PR TITLE
Adding responsiveTextFieldPlaceholderColor modifier to update a ResponsiveTextField's placeholder color

### PR DESCRIPTION
**Pull request by mergesort**

### CODE REVIEW

**Comment by mergesort** [comment]
I don't think this failure is me, I think it's flaky CI.

**Comment by lukeredpath** [comment]
LGTM - do you think you might be able to add a snapshot test?

**Comment by lukeredpath** [comment]
I need to update CI to use the correct simulator version as I think Xcode has been updated.

**Comment by mergesort** [comment]
Added a test, but I've never used snapshot tests so let me know if that works!

**Comment by lukeredpath** [comment]
@mergesort I just tried to update this to bring in the latest main and I think it updated your main branch. Can you try and revert the package changes in this PR please and I can get it merged in.

**Comment by mergesort** [comment]
Done!

**Comment by mergesort** [comment]
@lukeredpath Just as a heads up, I don't think the CI failures are cause of the code I changed.

**Pull request merged**
