### PR TITLE
Allow users to specify an accessibility identifier for the field

### PR DESCRIPTION
**Pull request by leopic**
While trying to write UI tests for a view using this package I realized there was no way to specify an identifier.

### CODE REVIEW

**Comment by lukeredpath** [comment]
@leopic thanks for the PR - out of interest, does attaching an identifier to the `ResponsiveTextView` using SwiftUI's accessibility APIs not work?

**Comment by leopic** [comment]
@lukeredpath it did not on my first attempt, let me try one more time before merging.

**Comment by lukeredpath** [comment]
@leopic actually, I think this might be better served using the existing configuration system, which would allow you to configure as many accessibility properties as you need, for example:

```swift
public extension ResponsiveTextField.Configuration {
  static func accessibile(identifier: String) {
    $0.accessibilityIdentifier = identifier
    // any other accessibility traits/properties set here
  }
}
```

And then pass this in when creating the text field:

```swift
...
configuration: .accessible(identifier: "foo")
```

Or if you're already using a configuration:

```swift
...
configuration: .combine(.someExisting, .accessible(identifier: "foo"))
```

**Comment by leopic** [comment]
@lukeredpath it did actually work, my bad!

No need for this PR at all, but I did like your approach better, to be honest 😅 .

Thanks anyway.

**Pull request closed without merging**
